---

# - name: shell module
#   shell: |
#     if [[ ($(hostname -I ) =~ ^172\.31\.) ]]; then
#       echo "dc1"
#     elif [[ ($(hostname -I ) =~ ^10\.([4-8])\.) || ($(hostname -I ) =~ ^10\.(3[0-5])\.)  ]]; then
#       echo "dc2"
#     elif [[ ($(hostname -I ) =~ ^10\.([0-3])\.) ]]; then
#       echo "dc3"
#     else
#       echo "default"
#     fi
#   register: vpc
- name: shell module
  shell: |
    if [[ ($(hostname -I ) =~ ^172\.31\.) ]]; then
      echo "dc1"
    elif [[ ($(hostname -I ) =~ ^10\.([4-8])\.) ]]; then
      echo "dc2"
    elif [[ ($(hostname -I ) =~ ^10\.([0-3])\.) ]]; then
      echo "dc3"
    else
      echo "default"
    fi
  register: vpc



- name: resolv conf template dc1
  template:
    src: template/dc1/mynresolve.conf
    dest: /etc/mynresolve.conf
    owner: root
    group: root
    mode: '0744'
  when: (vpc.stdout == "dc1")

- name: resolv conf template dc2
  template:
    src: template/dc2/mynresolve.conf
    dest: /etc/mynresolve.conf
    owner: root
    group: root
    mode: '0744'
  when: (vpc.stdout == "dc2")

- name: resolv conf template dc3
  template:
    src: template/dc3/mynresolve.conf
    dest: /etc/mynresolve.conf
    owner: root
    group: root
    mode: '0744'
  when: (vpc.stdout == "dc3")

- name: resolv conf template dfault
  template:
    src: template/default/mynresolve.conf
    dest: /etc/mynresolve.conf
    owner: root
    group: root
    mode: '0744'
  when: (vpc.stdout == "default")
