---

# creating directory on remote VMs
- name: create directory on remote VMs
  file:
    path: /etc/first
    state: directory
    owner: root
    group: root
    mode: 0644

# create a file name second
- name: create a file called second
  file:
    path: /etc/first/second
    owner: root
    group: root
    mode: 0644
    state: file

# install nginx on VMs
- name: install nginx on VMs
  package:
    name: nginx
    state: installed
